### ISSUE TITLE
Upgrade outdated libraries

### ISSUE THREAD

**Issue by andrewreshitko** [elasticio/sailor-jvm#98]
We have a [request from Infobip](https://elasticio.slack.com/archives/C01FLMQ0PB5/p1721642409550689) regarding an outdated library `org.eclipse.parsson:parsson`.
After the investigation, it was determined that Sailor contains a [few outdated libraries](https://elasticio.slack.com/archives/C6G1E4WB1/p1721642678665329).

**Comment by A3a3e1** [comment]
Blocked with https://github.com/elasticio/elasticio/issues/7539

The issue is that the Maven Central Repo does not allow to publish `-SNAPSHOT` versions anymore - https://central.sonatype.org/faq/snapshot-releases/

One possible option is deploying our own Maven repo, which is one more level of complexity for deploying, maintaining another system.
Other option is building a Sailor snapshot as a jar file and place it as a file into a target component.
